server:
  port: 8760

spring:
  application:
    name: eureka
  prefer-file-system-access: false


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

